2024-04-23 14:57:25,888 INFO    MainThread:68990 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-23 14:57:25,889 INFO    MainThread:68990 [wandb_setup.py:_flush():76] Configure stats pid to 68990
2024-04-23 14:57:25,889 INFO    MainThread:68990 [wandb_setup.py:_flush():76] Loading settings from /Users/danielskauge/.config/wandb/settings
2024-04-23 14:57:25,889 INFO    MainThread:68990 [wandb_setup.py:_flush():76] Loading settings from /Users/danielskauge/Documents/datasyn/lidar-object-detection/wandb/settings
2024-04-23 14:57:25,889 INFO    MainThread:68990 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-23 14:57:25,889 INFO    MainThread:68990 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-23 14:57:25,889 INFO    MainThread:68990 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'data_visualization.py', 'program_abspath': '/Users/danielskauge/Documents/datasyn/lidar-object-detection/data_visualization.py', 'program': '/Users/danielskauge/Documents/datasyn/lidar-object-detection/data_visualization.py'}
2024-04-23 14:57:25,889 INFO    MainThread:68990 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-23 14:57:25,889 INFO    MainThread:68990 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-04-23 14:57:25,890 INFO    MainThread:68990 [wandb_init.py:_log_setup():521] Logging user logs to /Users/danielskauge/Documents/datasyn/lidar-object-detection/wandb/run-20240423_145725-duu2tnyc/logs/debug.log
2024-04-23 14:57:25,890 INFO    MainThread:68990 [wandb_init.py:_log_setup():522] Logging internal logs to /Users/danielskauge/Documents/datasyn/lidar-object-detection/wandb/run-20240423_145725-duu2tnyc/logs/debug-internal.log
2024-04-23 14:57:25,890 INFO    MainThread:68990 [wandb_init.py:init():561] calling init triggers
2024-04-23 14:57:25,890 INFO    MainThread:68990 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-04-23 14:57:25,890 INFO    MainThread:68990 [wandb_init.py:init():611] starting backend
2024-04-23 14:57:25,890 INFO    MainThread:68990 [wandb_init.py:init():615] setting up manager
2024-04-23 14:57:25,897 INFO    MainThread:68990 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-04-23 14:57:25,900 INFO    MainThread:68990 [wandb_init.py:init():623] backend started and connected
2024-04-23 14:57:25,908 INFO    MainThread:68990 [wandb_init.py:init():715] updated telemetry
2024-04-23 14:57:25,958 INFO    MainThread:68990 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-23 14:57:26,387 ERROR   MainThread:68990 [wandb_init.py:init():774] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-23 14:57:26,505 ERROR   MainThread:68990 [wandb_init.py:init():1199] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
          ^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-23 14:57:27,539 WARNING MsgRouterThr:68990 [router.py:message_loop():77] message_loop has been closed
